/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Route generation was removed when the project was converted to a client-only SPA.
// This file has been stubbed to avoid build errors from tools that might still import it.

export const routeTree = undefined as any
